version: 0.0
os: linux
files:
  - source: /
    destination: /usr/share/nginx/html
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/start_nginx.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/restart_nginx.sh
      timeout: 300
      runas: root

  ValidateService:
    - location: scripts/validate_nginx.sh
      timeout: 300
      runas: root
